### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by metalivedev** [mootools/slick#76]
Please add a License file or add a license to the code headers.
If it is there, I'm sorry I missed it.

**Comment by SergioCrisostomo** [comment]
hi @metalivedev! The license information can be found [in the `.yml` file of the repository.](https://github.com/mootools/slick/blob/master/package.yml#L7)

I hope that was what you were looking for!
Cheers

**Comment by metalivedev** [comment]
Perfect, thanks!
