### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by metalivedev** [mootools/slick#78]
Does having a license in package.yml carry the same weight as including the LICENSE file explicitly? If not, could you include a LICENSE file in this repo?

**Comment by scottgonzalez** [comment]
Well, regardless of whether it would legally hold up in court, it's impossible the comply with the MIT license without having the actual license written out. The license explicitly requires the copyright notice and the license text to be included in all copies of the software.

**Comment by subtleGradient** [comment]
https://github.com/mootools/slick/blob/master/LICENSE.txt this one?

**Comment by scottgonzalez** [comment]
🤣  Yes, that one. Looks like this issue was resolved within two hours of the issue being opened... 9 years ago.
